<?php

namespace NextDeveloper\Support\Services;

use Illuminate\Http\Request;
use NextDeveloper\IAM\Helpers\UserHelper;
use NextDeveloper\Support\Database\Filters\TicketsQueryFilter;
use NextDeveloper\Support\Database\Models\Tickets;
use NextDeveloper\Support\Services\AbstractServices\AbstractTicketsService;

/**
 * This class is responsible from managing the data for Tickets
 *
 * Class TicketsService.
 *
 * @package NextDeveloper\Support\Database\Models
 */
class TicketsService extends AbstractTicketsService
{

    // EDIT AFTER HERE - WARNING: ABOVE THIS LINE MAY BE REGENERATED AND YOU MAY LOSE CODE
    public static function update($id, array $data)
    {
        // We are removing this because we don't want to update the time spent on the ticket
        // This is because the time spent is calculated automatically
        if (array_key_exists('time_spent', $data))
            unset($data['time_spent']);

        return parent::update($id, $data);
    }

    public static function create(array $data)
    {
        if(array_key_exists('support_seeker_account_id', $data)) {
            //  Here we will send the support seeker an email
        } else {
            //  This means that ticket is created by the account owner
            $data['support_seeker_account_id'] = UserHelper::currentAccount()->id;
        }

        return parent::create($data); // TODO: Change the autogenerated stub
    }
}
